### ISSUE TITLE
Add white spacing back in

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/vdl-logo#1]
The original log has some spacing between the bars and the flask:

![image](https://user-images.githubusercontent.com/2039375/44950530-24311280-ae07-11e8-8259-b0e787fd08df.png)

For consistency, and also or aesthetics, we also want that in the animated logo. 

I don't know whether we want to have that spacing also or the bubbles; in the original logo they are clipped, but we don't want/need that.

**Comment by kirangadhave** [comment]
Added the spacing.
